### ISSUE TITLE
Add seperate rx/vn leaderboards

### ISSUE THREAD

**Issue by Lekuruu** [osuTitanic/titanic#7]
A lot of people have requested to separate rx/vn leaderboards entirely, and I agree on that as well. At first I thought, making the pp system balanced enough would work, but that does not seem to be the case. To not completely restructure the way, the server works right now, I've come up with a new solution.
My Idea is to still combine rx & vn scores for pp ranks, but also making separate leaderboard for rx and vn at the same time. The rx/vn rank will get displayed on their profile if they choose so in the settings. Based on user feedback, I may or may not implement this in the future.

**Comment by kanaarima** [comment]
I think having separate ranks (Unified/VN/RX/AP)  show in user profile page is enough.
Unified leaderboard can work with a balanced pp system and adjustments to score (which is mostly done right now) IMO

**Comment by Lekuruu** [comment]
The rx/vn rank tracking was implemented, but it is very unlikely that I will seperate both of them in the near future.
